recipe: update to GDB 11.1
Note that GDB now requires GMP (the GNU Multiple Precision Arithmetic
Library), so add it to the host requirements.

Note also that we update to the CentOS 7 sysroot package on Linux; this
is necessary to avoid a catastrophic build failure in GDB's import of
gnulib starting with:

    /home/conda/feedstock_root/build_artifacts/debug_1634397249295/work/gnulib/import/glob.c: In function 'next_brace_sub':
    /home/conda/feedstock_root/build_artifacts/debug_1634397249295/work/gnulib/import/glob.c:89:66: error: expected declaration specifiers before '__THROWNL'
       89 | static const char *next_brace_sub (const char *begin, int flags) __THROWNL;
          |                                                                  ^~~~~~~~~

The header 'cdefs.h' from the new sysroot does define '__THROWNL'. [2]

[1] https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=gdb/NEWS;hb=gdb-11.1-release
[2] https://public-inbox.org/bug-gnulib/87im6h1i3j.fsf@tromey.com/t/#u