recipe: add '-D_LIBCPP_DISABLE_AVAILABILITY' on macOS
The libc++ library uses Clang availability annotations to mark certain
symbols as unavailable when targeting versions of macOS that ship with a
system libc++ that do not contain them [1]. Clang always assumes that
the system libc++ is used, unless the preprocessor macro
'-D_LIBCPP_DISABLE_AVAILABILITY' is defined.

The conda-forge build infrastructure targets macOS 10.9, and some
symbols used by the GDB build are marked as unavailable on that
platform, so the build aborts:

~~~
In file included from
/Users/travis/miniforge3/conda-bld/gdb_1624919890661/work/gdb/x86-nat.c:23:
Users/travis/miniforge3/conda-bld/gdb_1624919890661/work/gdb/inferior.h:87:19:
error: 'uncaught_exceptions' is unavailable: introduced in macOS 10.12
        unwinding = std::uncaught_exceptions () > 0;
                         ^
/Users/travis/miniforge3/conda-bld/gdb_1624919890661/_build_env/bin/../include/c++/v1/exception:132:63:
note: 'uncaught_exceptions' has been explicitly marked unavailable here
_LIBCPP_FUNC_VIS _LIBCPP_AVAILABILITY_UNCAUGHT_EXCEPTIONS int uncaught_exceptions() _NOEXCEPT;
                                                              ^
1 error generated.
~~~

As we are building with conda-forge's build of libc++, and not the
system version of macOS 10.9, these symbols are in fact available, so
disable the availability check, as recommended at [3].

[1] https://github.com/llvm/llvm-project/blob/b9c24257c7b4da398798934ffefdd30015152180/libcxx/include/__availability#L19-L68
[2] https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks
[3] https://gitter.im/conda-forge/conda-forge.github.io?at=5f5bb7124f19dd093342068c